### ISSUE TITLE
页面切换的动画有些问题

### ISSUE THREAD

**Issue by zhouxin1233** [hightman/getx5-example_nav2#2]
比如说从第三个tab跳转到另一个页面的时候， 放慢页面过度动画 会显示出来第一个tab页面 然后再跳转切换

https://github.com/user-attachments/assets/728ffd0d-b4d2-49b7-b4bd-d305c69fe7b3

**Comment by hightman** [comment]
ok，晚点处理一下，url变化导致home view一些设定出现问题发自我的 iPhone6艹在 2024年7月31日，19:07，小新哥哥 ***@***.***> 写道：﻿
The over-animated transition effect is incorrect when switching pages.
https://github.com/user-attachments/assets/728ffd0d-b4d2-49b7-b4bd-d305c69fe7b3
